version: '3.9'

services:
  server:
    build: ./server
    ports:
      - "5050:5050"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/app
    networks:
      - kanban-net

  client:
    build: ./client
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - server
    networks:
      - kanban-net

networks:
  kanban-net:
